### ISSUE TITLE
main@{1day}...main

### ISSUE THREAD

**Issue by mhwdrda2** [catpuppyapp/PuppyGit#16]
<head>body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    color: #333;
    text-align: center;
    margin: 0;
    padding: 0;
}

h1 {
    color: #007bff;
}

p {
    font-size: 18px;
}img {
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}a {
    color: #007bff;
    text-decoration: none;
}
a:hover {
    text-decoration: underline;
    color: #0056b3;
}form {
    width: 300px;
    margin: 20px auto;
    text-align: left;
}
input, button {
    width: 100%;
    padding: 10px;
    margin: 5px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
}
button {
    background-color: #007bff;
    color: white;
    border: none;
    cursor: pointer;
}
button:hover {
    background-color: #0056b3;
}@media (max-width: 600px) {
    body {
        font-size: 14px;
    }
    table {
        width: 100%;
    }
    form {
        width: 90%;
    }
}

Uploading VID_20241207_061452_441.mp4…

**Comment by Bandeapart1964** [comment]
what are you doing?
