### ISSUE TITLE
error cloning via ssh url

### ISSUE THREAD

**Issue by clach04** [catpuppyapp/PuppyGit#7]
Error in UI:

    authentication required but no callback set (2024-11-20 20:56:30,timestamp)

EDIT resolved, see below.

Are there any other logs I can capture to show what happened?

Key used generated with https://github.com/catpuppyapp/SshKeyMan/releases/tag/1.3v4

**Comment by clach04** [comment]
This may be a user error, I later realized I left the key entry (copy and paste failure) 😆 The error initially confused me.

I have successfully cloned a repo now 🎉

**Comment by Bandeapart1964** [comment]
`authentication required but no callback set (2024-11-20 20:56:30,timestamp)` 

this err usually occur when required authentication but no linked the credential in PuppyGit.

and glad now resolved😊
