### ISSUE TITLE
Idea, in file browser have an option to change display/sort order

### ISSUE THREAD

**Issue by clach04** [catpuppyapp/PuppyGit#8]
Ascending / Descending for:

  1. name
  2. date
  3. size

**Comment by Bandeapart1964** [comment]
yup, sure, it should has, I plan support them in furture, for now, maybe try external files manager instead.

e.g. [Material Files](https://github.com/zhanghai/MaterialFiles)

**Comment by Bandeapart1964** [comment]
next version will add this feature

**Comment by Bandeapart1964** [comment]
try new version: https://github.com/catpuppyapp/PuppyGit/releases


![FilesSort1](https://github.com/user-attachments/assets/a16f1465-d246-403b-bf58-5c92ddbfc2ee)
![FilesSort2](https://github.com/user-attachments/assets/41c8484f-e236-4af1-9436-90fe8ee75002)

**Comment by clach04** [comment]
Works great! Nice work 👍
