### ISSUE TITLE
built-in text editor doesn't support .md file extension

### ISSUE THREAD

**Issue by clach04** [catpuppyapp/PuppyGit#9]
I'm not sure if this is a bug report or a feature request. The built in text editor can open .txt files but not .md. Instead the option to open with an external editor is shown.

**Comment by Bandeapart1964** [comment]
cause PuppyGit internal editor doesn't support  md format, no sytax highlight and preview, so as default when you clicked a .md or .markdown file, it will show a open as dialog , but you can click the "Open in Editor" using internal editor open it or any other format files (see the image below), and actually I using markor edit markdown files for now, I have no plan support markdown format for PuppyGit now.
![openas](https://github.com/user-attachments/assets/bfde8d5d-904d-480f-8f86-245f8693442d)

**Comment by clach04** [comment]
Thanks! Open in editor, did open in the built-in editor  (just needs an extra click). Understood about markdown support. I agree it doesn't seem worth the effort for a git client.

**Comment by clach04** [comment]
Cross reference:

  * #35
